#########################################
# RPM-specific Makefile			#
# https://yum.gunduzdanismanlik.com	#
#                         		#
# Devrim Gunduz				#
# devrim@gunduz.org			#
#########################################

# Predefined values

ARCH=`rpm --eval "%{_arch}"`
DIR=`pwd`
DIST=.rhel7
SPECFILE="gbdsql-11.spec"

# Now, include global Makefile
include ../../../common/Makefile.global
