#################################
# RPM-specific Makefile		#
# https://yum.postgresql.org	#
#                         	#
# Devrim Gunduz           	#
# devrim@gunduz.org        	#
#################################

# Predefined values

ARCH=`rpm --eval "%{_arch}"`
DIR=`pwd`
DIST=.rhel7
SPECFILE="gdal23.spec"

# Now, include global Makefile
include ../../../common/Makefile.global
