#########################################
# General Makefile 		   	#
# for RPM packaging		   	#
# https://yum.gunduzdanismanlik.com	#
#			   		#
# Devrim Gunduz		   		#
# devrim@gunduzdanismanlik.com 		#
#########################################
#			 		#
# build target is for      		#
# RPM buildfarm		   		#
#			   		#
#########################################

# Predefined values

ARCH=`rpm --eval "%{_arch}"`
DIR=`pwd`
DIST=.rhel7
SPECFILE="gbd-pgagent.spec"

# Now, include global Makefile
include ../../../common/Makefile.global
