#########################################
# General Makefile			#
# for RPM packaging			#
# https://yum.gunduzdanismanlik.com	#
#					#
# Devrim Gunduz				#
# devrim@gunduzdanismanlik.com		#
#########################################
#					#
#					#
# build target is for			#
# RPM buildfarm				#
#					#
#					#
#########################################

## PostgreSQL 11 Testing

prep11testing:
	if [ -f dead.package ]; then echo "This package is marked as dead. Build won't continue"; exit 1; fi
	# Update spec file, patches, etc, before running spectool:
	git pull
	# Use spectool to download source files, especially tarballs.
	spectool -g -S --define "pgmajorversion 11" --define "pginstdir /usr/pgsql-11" --define "pgpackageversion 11" $(SPECFILE)

build11testing: bfsrpm11testing
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define "_buildrootdir $(HOME)/rpm11testing/BUILDROOT" \
	--define "_builddir $(HOME)/rpm11testing/BUILD" \
	--define "_srcrpmdir $(HOME)/rpm11testing/SRPMS" \
	--define "_rpmdir $(HOME)/rpm11testing/RPMS/" --sign \
	--define "pgmajorversion 11" --define "pginstdir /usr/pgsql-11" --define "pgpackageversion 11" \
	--define "dist $(DIST)" -bb $(SPECFILE)

srpm11testing: prep11
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir ." --sign \
	--define "_buildrootdir $(HOME)/rpm11testing/BUILDROOT" \
	--define "pgmajorversion 11" --define "pginstdir /usr/pgsql-11"  --define "pgpackageversion 11" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

bfsrpm11testing: prep11
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir $(HOME)/rpm11testing/SRPMS" --sign \
	--define "_buildrootdir $(HOME)/rpm11testing/BUILDROOT" \
	--define "pgmajorversion 11" --define "pginstdir /usr/pgsql-11"  --define "pgpackageversion 11" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

bfnosignsrpm11testing: prep11
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_buildrootdir $(HOME)/rpm11testing/BUILDROOT" \
	--define "_builddir ." --define "_srcrpmdir $(HOME)/rpm11testing/SRPMS" \
	--define "pgmajorversion 11" --define "pginstdir /usr/pgsql-11"  --define "pgpackageversion 11" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

rpm11testing: prep11
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(PWD)" \
	--define "_buildrootdir $(HOME)/rpm11testing/BUILDROOT" \
	--define "_srcrpmdir $(PWD)" \
	--define "_rpmdir $(PWD)" \
	--define "pgmajorversion 11" --define "pginstdir /usr/pgsql-11" --define "pgpackageversion 11" \
	--define "dist $(DIST)" -bb $(SPECFILE)

nosignbuild11testimg: bfnosignsrpm11testing
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(HOME)/rpm11testing/BUILD" \
	--define "_buildrootdir $(HOME)/rpm11testing/BUILDROOT" \
	--define "_srcrpmdir $(HOME)/rpm11testing/SRPMS" \
	--define "_rpmdir $(HOME)/rpm11testing/RPMS/" \
	--define "pgmajorversion 11" --define "pginstdir /usr/pgsql-11" --define "pgpackageversion 11" \
	--define "dist $(DIST)" -bb $(SPECFILE)

noprepbuild11testing:
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir $(HOME)/rpm11testing/SRPMS" --sign \
	--define "_buildrootdir $(HOME)/rpm11testing/BUILDROOT" \
	--define "pgmajorversion 11" --define "pginstdir /usr/pgsql-11" --define "pgpackageversion 11" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(HOME)/rpm11testing/BUILD" \
	--define "_buildrootdir $(HOME)/rpm11testing/BUILDROOT" \
	--define "_srcrpmdir $(HOME)/rpm11testing/SRPMS" \
	--define "_rpmdir $(HOME)/rpm11testing/RPMS/" --sign \
	--define "pgmajorversion 11" --define "pginstdir /usr/pgsql-11" --define "pgpackageversion 11" \
	--define "dist $(DIST)" -bb $(SPECFILE)

nopreprpm11testing:
	rpmbuild --define "_sourcedir $(PWD)" \
	--define "_specdir $(PWD)" \
	--define  "_builddir $(PWD)" \
	--define "_buildrootdir $(HOME)/rpm11testing/BUILDROOT" \
	--define "_srcrpmdir $(PWD)" \
	--define "_rpmdir $(PWD)" \
	--define "pgmajorversion 11" --define "pginstdir /usr/pgsql-11" --define "pgpackageversion 11" \
	--define "dist $(DIST)" -bb $(SPECFILE)

noprepsrpm11testing:
	rpmbuild --define "_sourcedir ." --define "_specdir ." \
	--define "_builddir ." --define "_srcrpmdir ." \
	--define "_buildrootdir $(HOME)/rpm11testing/BUILDROOT" \
	--define "pgmajorversion 11" --define "pginstdir /usr/pgsql-11" --define "pgpackageversion 11" \
	--define "_rpmdir ." --define "dist $(DIST)" --nodeps -bs $(SPECFILE)

